const companies = [
  {"slug": "abbott-laboratories","name": "Abbott Laboratories","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "abbvie","name": "AbbVie Inc.","industry": "Healthcare & Pharmaceuticals","score": 6,"max_score": 7},
  {"slug": "albertsons","name": "Albertsons Companies, Inc.","industry": "Consumer Goods & Staples","score": 3,"max_score": 7},
  {"slug": "alphabet","name": "Alphabet Inc.","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "amazon","name": "Amazon.com, Inc.","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "american-airlines","name": "American Airlines Group Inc.","industry": "Airlines","score": 5.5,"max_score": 7},
  {"slug": "american-express","name": "American Express Company","industry": "Financial Services","score": 6,"max_score": 7},
  {"slug": "apple","name": "Apple Inc.","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "archer-daniels-midland","name": "Archer-Daniels-Midland Company","industry": "Food & Beverage","score": 4.5,"max_score": 7},
  {"slug": "att","name": "AT&T Inc.","industry": "Telecommunications","score": 7,"max_score": 7},
  {"slug": "bank-of-america","name": "Bank of America Corporation","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "berkshire-hathaway","name": "Berkshire Hathaway Inc.","industry": "Conglomerate","score": 3.0,"max_score": 7},
  {"slug": "best-buy","name": "Best Buy Co., Inc.","industry": "Retail","score": 7,"max_score": 7},
  {"slug": "bristol-myers-squibb","name": "Bristol-Myers Squibb Company","industry": "Healthcare & Pharmaceuticals","score": 6,"max_score": 7},
  {"slug": "broadcom","name": "Broadcom Inc.","industry": "Semiconductors","score": 7,"max_score": 7},
  {"slug": "capital-one","name": "Capital One Financial Corporation","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "cardinal-health","name": "Cardinal Health, Inc.","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "caterpillar","name": "Caterpillar Inc.","industry": "Construction & Machinery","score": 6,"max_score": 7},
  {"slug": "cbre-group","name": "CBRE Group, Inc.","industry": "Real Estate","score": 7,"max_score": 7},
  {"slug": "cencora","name": "Cencora, Inc.","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "centene","name": "Centene Corporation","industry": "Healthcare & Pharmaceuticals","score": 6,"max_score": 7},
  {"slug": "charter-communications","name": "Charter Communications, Inc.","industry": "Telecommunications","score": 1.5,"max_score": 7},
  {"slug": "chevron","name": "Chevron Corporation","industry": "Energy & Oil & Gas","score": 7,"max_score": 7},
  {"slug": "chs","name": "CHS Inc.","industry": "Agriculture","score": 4,"max_score": 7},
  {"slug": "cisco-systems","name": "Cisco Systems, Inc.","industry": "Telecommunications","score": 7,"max_score": 7},
  {"slug": "citigroup","name": "Citigroup Inc.","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "comcast","name": "Comcast Corporation","industry": "Media & Entertainment","score": 3.5,"max_score": 7},
  {"slug": "conocophillips","name": "ConocoPhillips Company","industry": "Energy & Oil & Gas","score": 2.5,"max_score": 7},
  {"slug": "costco-wholesale","name": "Costco Wholesale Corporation","industry": "Retail","score": 6.5,"max_score": 7},
  {"slug": "cvs-health","name": "CVS Health Corporation","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "dr-horton","name": "D.R. Horton, Inc.","industry": "Construction & Machinery","score": 0,"max_score": 7},
  {"slug": "deere","name": "Deere & Company","industry": "Construction & Machinery","score": 7,"max_score": 7},
  {"slug": "dell-technologies","name": "Dell Technologies Inc.","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "delta-air-lines","name": "Delta Air Lines, Inc.","industry": "Airlines","score": 4,"max_score": 7},
  {"slug": "dollar-general","name": "Dollar General Corporation","industry": "Retail","score": 2.5,"max_score": 7},
  {"slug": "dow","name": "Dow Inc.","industry": "Chemicals","score": 4.0,"max_score": 7},
  {"slug": "elevance-health","name": "Elevance Health, Inc.","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "eli-lilly","name": "Eli Lilly and Company","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "energy-transfer","name": "Energy Transfer LP","industry": "Energy & Oil & Gas","score": 0,"max_score": 7},
  {"slug": "enterprise-products-partners","name": "Enterprise Products Partners L.P.","industry": "Energy & Oil & Gas","score": 0,"max_score": 7},
  {"slug": "exxon-mobile","name": "Exxon Mobil Corporation","industry": "Energy & Oil & Gas","score": 3.0,"max_score": 7},
  {"slug": "freddie-mac","name": "Federal Home Loan Mortgage Corporation","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "fannie-mae","name": "Federal National Mortgage Association","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "fedex","name": "FedEx Corporation","industry": "Logistics & Transportation","score": 7,"max_score": 7},
  {"slug": "ford-motor","name": "Ford Motor Company","industry": "Automotive","score": 7,"max_score": 7},
  {"slug": "ge-vernova","name": "GE Vernova Inc.","industry": "Energy & Oil & Gas","score": 6,"max_score": 7},
  {"slug": "general-dynamics","name": "General Dynamics Corporation","industry": "Aerospace & Defense","score": 5,"max_score": 7},
  {"slug": "general-electric","name": "General Electric Company","industry": "Industrials","score": 7,"max_score": 7},
  {"slug": "general-motors","name": "General Motors Company","industry": "Automotive","score": 7,"max_score": 7},
  {"slug": "hca-healthcare","name": "HCA Healthcare, Inc.","industry": "Healthcare & Pharmaceuticals","score": 6,"max_score": 7},
  {"slug": "honeywell","name": "Honeywell International Inc.","industry": "Conglomerate","score": 7,"max_score": 7},
  {"slug": "hp","name": "HP Inc.","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "humana","name": "Humana Inc.","industry": "Insurance","score": 6.5,"max_score": 7},
  {"slug": "ingram-micro","name": "Ingram Micro Holding Corporation","industry": "Information Technology","score": 7,"max_score": 7},
  {"slug": "intel","name": "Intel Corporation","industry": "Semiconductors","score": 7,"max_score": 7},
  {"slug": "ibm","name": "International Business Machines Corporation","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "johnson-johnson","name": "Johnson & Johnson","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "jpmorgan-chase","name": "JPMorgan Chase & Co.","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "lennar","name": "Lennar Corporation","industry": "Construction & Machinery","score": 5,"max_score": 7},
  {"slug": "liberty-mutual-insurance","name": "Liberty Mutual Insurance Company","industry": "Insurance","score": 7,"max_score": 7},
  {"slug": "lithia-motors","name": "Lithia Motors, Inc.","industry": "Automotive","score": 1,"max_score": 7},
  {"slug": "live-nation-entertainment","name": "Live Nation Entertainment, Inc.","industry": "Media & Entertainment","score": 4,"max_score": 7},
  {"slug": "lockheed-martin","name": "Lockheed Martin Corporation","industry": "Aerospace & Defense","score": 7,"max_score": 7},
  {"slug": "lowes","name": "Lowe's Companies, Inc.","industry": "Retail","score": 6,"max_score": 7},
  {"slug": "marathon-petroleum","name": "Marathon Petroleum Corporation","industry": "Energy & Oil & Gas","score": 5,"max_score": 7},
  {"slug": "massmutual","name": "Massachusetts Mutual Life Insurance Company","industry": "Insurance","score": 5,"max_score": 7},
  {"slug": "mckesson","name": "McKesson Corporation","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "merck-co","name": "Merck & Co., Inc.","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "meta-platforms","name": "Meta Platforms, Inc.","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "metlife","name": "MetLife, Inc.","industry": "Insurance","score": 4,"max_score": 7},
  {"slug": "microsoft","name": "Microsoft Corporation","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "molina-healthcare","name": "Molina Healthcare, Inc.","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "mondelez-international","name": "Mondelez International, Inc.","industry": "Food & Beverage","score": 3,"max_score": 7},
  {"slug": "morgan-stanley","name": "Morgan Stanley","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "nationwide","name": "Nationwide Mutual Insurance Company","industry": "Financial Services","score": 6,"max_score": 7},
  {"slug": "netflix","name": "Netflix, Inc.","industry": "Media & Entertainment","score": 5,"max_score": 7},
  {"slug": "new-york-life-insurance","name": "New York Life Insurance Company","industry": "Insurance","score": 7,"max_score": 7},
  {"slug": "nike","name": "Nike, Inc.","industry": "Apparel & Footwear","score": 6,"max_score": 7},
  {"slug": "northrop-grumman","name": "Northrop Grumman Corporation","industry": "Aerospace & Defense","score": 7,"max_score": 7},
  {"slug": "northwestern-mutual","name": "Northwestern Mutual Life Insurance Company","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "nvidia","name": "NVIDIA Corporation","industry": "Semiconductors","score": 7,"max_score": 7},
  {"slug": "oracle","name": "Oracle Corporation","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "pepsico","name": "PepsiCo, Inc.","industry": "Food & Beverage","score": 7,"max_score": 7},
  {"slug": "performance-food-group","name": "Performance Food Group Company","industry": "Food & Beverage","score": 3.0,"max_score": 7},
  {"slug": "pfizer","name": "Pfizer Inc.","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "philip-morris-international","name": "Philip Morris International Inc.","industry": "Tobacco","score": 5,"max_score": 7},
  {"slug": "phillips-66","name": "Phillips 66 Company","industry": "Energy & Oil & Gas","score": 7,"max_score": 7},
  {"slug": "plains-gp","name": "Plains GP Holdings, L.P.","industry": "Energy & Oil & Gas","score": 0,"max_score": 7},
  {"slug": "prudential-financial","name": "Prudential Financial, Inc.","industry": "Financial Services","score": 6,"max_score": 7},
  {"slug": "publix-super-markets","name": "Publix Super Markets, Inc.","industry": "Retail","score": 6,"max_score": 7},
  {"slug": "qualcomm","name": "Qualcomm Incorporated","industry": "Telecommunications","score": 6,"max_score": 7},
  {"slug": "rtx","name": "RTX Corporation","industry": "Aerospace & Defense","score": 5.5,"max_score": 7},
  {"slug": "salesforce","name": "Salesforce, Inc.","industry": "Technology","score": 7,"max_score": 7},
  {"slug": "starbucks","name": "Starbucks Corporation","industry": "Retail","score": 7,"max_score": 7},
  {"slug": "state-farm","name": "State Farm Mutual Automobile Insurance Company","industry": "Insurance","score": 5.5,"max_score": 7},
  {"slug": "stonex-group","name": "StoneX Group Inc.","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "sysco","name": "Sysco Corporation","industry": "Food & Beverage","score": 5,"max_score": 7},
  {"slug": "target","name": "Target Corporation","industry": "Retail","score": 0.5,"max_score": 7},
  {"slug": "td-synnex","name": "TD SYNNEX Corporation","industry": "Electronics & Distribution","score": 7,"max_score": 7},
  {"slug": "tiaa","name": "Teachers Insurance and Annuity Association of America","industry": "Financial Services","score": 6,"max_score": 7},
  {"slug": "tesla","name": "Tesla, Inc.","industry": "Automotive","score": 6.5,"max_score": 7},
  {"slug": "allstate","name": "The Allstate Corporation","industry": "Insurance","score": 6.5,"max_score": 7},
  {"slug": "bank-of-new-york-mellon","name": "The Bank of New York Mellon Corporation","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "boeing","name": "The Boeing Company","industry": "Aerospace & Defense","score": 6.5,"max_score": 7},
  {"slug": "cigna","name": "The Cigna Group","industry": "Insurance","score": 7,"max_score": 7},
  {"slug": "coca-cola-company","name": "The Coca-Cola Company","industry": "Beverages","score": 3,"max_score": 7},
  {"slug": "goldman-sachs","name": "The Goldman Sachs Group, Inc.","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "home-depot","name": "The Home Depot, Inc.","industry": "Retail","score": 5.5,"max_score": 7},
  {"slug": "kroger","name": "The Kroger Co.","industry": "Retail","score": 7,"max_score": 7},
  {"slug": "procter-gamble","name": "The Procter & Gamble Company","industry": "Consumer Goods & Staples","score": 4,"max_score": 7},
  {"slug": "progressive","name": "The Progressive Corporation","industry": "Insurance","score": 5,"max_score": 7},
  {"slug": "tjx","name": "The TJX Companies, Inc.","industry": "Retail","score": 2.5,"max_score": 7},
  {"slug": "travelers","name": "The Travelers Companies, Inc.","industry": "Insurance","score": 6.5,"max_score": 7},
  {"slug": "walt-disney","name": "The Walt Disney Company","industry": "Media & Entertainment","score": 7,"max_score": 7},
  {"slug": "thermo-fisher-scientific","name": "Thermo Fisher Scientific Inc.","industry": "Biotechnology","score": 7,"max_score": 7},
  {"slug": "tyson-foods","name": "Tyson Foods, Inc.","industry": "Food & Beverage","score": 7,"max_score": 7},
  {"slug": "us-bancorp","name": "U.S. Bancorp","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "uber","name": "Uber Technologies, Inc.","industry": "Logistics & Transportation","score": 7,"max_score": 7},
  {"slug": "united-airlines","name": "United Airlines Holdings, Inc.","industry": "Airlines","score": 3,"max_score": 7},
  {"slug": "ups","name": "United Parcel Service, Inc.","industry": "Logistics & Transportation","score": 5.5,"max_score": 7},
  {"slug": "usaa","name": "United Services Automobile Association","industry": "Financial Services","score": 6,"max_score": 7},
  {"slug": "unitedhealth-group","name": "UnitedHealth Group Incorporated","industry": "Healthcare & Pharmaceuticals","score": 7,"max_score": 7},
  {"slug": "us-foods","name": "US Foods Holding Corp.","industry": "Food & Beverage","score": 5,"max_score": 7},
  {"slug": "valero-energy","name": "Valero Energy Corporation","industry": "Energy & Oil & Gas","score": 1,"max_score": 7},
  {"slug": "verizon","name": "Verizon Communications Inc.","industry": "Telecommunications","score": 7,"max_score": 7},
  {"slug": "visa","name": "Visa Inc.","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "walgreens-boots-alliance","name": "Walgreens Boots Alliance, Inc.","industry": "Healthcare & Pharmaceuticals","score": 6,"max_score": 7},
  {"slug": "walmart","name": "Walmart Inc.","industry": "Retail","score": 7,"max_score": 7},
  {"slug": "warner-bros-discovery","name": "Warner Bros. Discovery, Inc.","industry": "Media & Entertainment","score": 3.5,"max_score": 7},
  {"slug": "wells-fargo","name": "Wells Fargo & Company","industry": "Financial Services","score": 7,"max_score": 7},
  {"slug": "world-kinect","name": "World Kinect Corporation","industry": "Energy & Oil & Gas","score": 1.5,"max_score": 7}
].sort((a, b) => a.name.localeCompare(b.name));